import { Metadata } from "next";

export type MetadataProps = {
	title?: string;
	description?: string;
	banner?: string;
	path?: string;
	allowIndexing?: boolean;
};

const BaseTitle = "Luminosity - Explaining complex topics with simple videos";
const BaseDescription =
	"Luminosity is a platform that explains complex topics with simple videos, all generated by AI.";

export function createMetadata(props: MetadataProps = {}) {
	return {
		metadataBase: new URL(
			process.env.NEXT_PUBLIC_BASE_URL + (props.path ?? "/")
		),
		title: props.title ?? BaseTitle,
		description: props.description ?? BaseDescription,
		authors: [
			{
				name: "Landon Harter",
				url: "https://landonharter.me",
			},
		],
		publisher: "Luminosity",
		robots: {
			index: props.allowIndexing ?? true,
			follow: props.allowIndexing ?? true,
		},
		creator: "Landon Harter",
		applicationName: "Luminosity",
		icons: [
			{
				url: process.env.NEXT_PUBLIC_BASE_URL + "/brand/favicon.ico",
			},
		],
		openGraph: {
			title: props.title ?? BaseTitle,
			description: props.description ?? BaseDescription,
			url: process.env.NEXT_PUBLIC_BASE_URL + (props.path ?? "/"),
			type: "website",
			siteName: "Luminosity",
			images: [
				{
					url:
						props.banner ||
						process.env.NEXT_PUBLIC_BASE_URL + "/brand/logo.png",
				},
			],
		},
		twitter: {
			cardType: "summary_large_image",
			site: process.env.NEXT_PUBLIC_BASE_URL,
			title: props.title ?? BaseTitle,
			description: props.description ?? BaseDescription,
			images: [
				{
					url:
						props.banner ||
						process.env.NEXT_PUBLIC_BASE_URL + "/brand/logo.png",
				},
			],
		},
		alternates: {
			canonical: process.env.NEXT_PUBLIC_BASE_URL + (props.path ?? "/"),
			languages: {
				"en-US": process.env.NEXT_PUBLIC_BASE_URL + (props.path ?? "/"),
			},
		},
	} as Metadata;
}
