name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Azure Container Registry
      run: docker login luminosity.azurecr.io --username luminosity --password-stdin <<< ${{ secrets.LUMINOSITY_CONTAINER_REGISTRY_PASSWORD }}
    - name: Build Docker Image
      run: docker build -t luminosity.azurecr.io/luminosity .
    - name: Push Docker Image
      run: docker push luminosity.azurecr.io/luminosity